name: portfolio
description: A new Flutter project.

publish_to: 'none' 
version: 1.2.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  flutter_icons: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/projects_previews/
  uses-material-design: true                                     