name: portfolio
description: A new Flutter project.

publish_to: 'none' 
version: 1.4.1+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.6
  flutter_icons: ^1.1.0

  # Firebase
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_analytics: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true                                     
